# Generated by Django 5.1.7 on 2025-03-31 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_due_date_alter_task_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='plan_order',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='planned',
            field=models.BooleanField(default=False),
        ),
    ]
